### ISSUE TITLE
Results are unreadable

### ISSUE THREAD

**Issue by JerichoCross** [arnaud-carre/abc#2]
I have tried converting four different images to both HAM and SHAM but I am unable to view them on an emulated A500. I am using shamview that I got from Aminet but I either get corrupted images or a blank window. The command lines I used were:

abc2 forest.png -ham -floyd -iff forestHAM.iff
abc2 forest.png -sham -floyd -iff forestSHAM.iff

These seem to produce unreadable image files.

**Comment by arnaud-carre** [comment]
this is not expected. Did you tried to open -ham .iff image on PC using XnView? at least it works for me
